# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 63abc2d
_src_path: gh:goodcleanfun/clib-template
description: Generic heap data structures in C
has_src: true
license: MIT
name: heaps
repo_org: goodcleanfun

